Update Jenkinsfile

diff --git a/task1/Jenkinsfile b/task1/Jenkinsfile
--- a/task1/Jenkinsfile
+++ b/task1/Jenkinsfile
@@ -18,10 +18,6 @@ pipeline {
 
         stage('Preparation') {
             steps {
-                sh 'pwd'
-                sh 'ls -al'
-                
-                // Check for the presence of ansible.yml inside the microK8s directory
                 script {
                     if (!fileExists('task1/microk8s/ansible.yml')) {
                         error("ansible.yml is missing in the task1/microk8s directory!")
@@ -30,117 +26,39 @@ pipeline {
             }
         }
 
-        stage('AWS Infra Deployment via terraform') {
+        stage('AWS Infra Deployment via Terraform') {
             steps {
-                withCredentials([
-                    [$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'AWS_Access', accessKeyVariable: 'AWS_ACCESS_KEY_ID', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'],
-                    sshUserPrivateKey(credentialsId: 'sec_com_ass_key_pair', keyFileVariable: 'SSH_KEY_PATH')
-                ]) {
-                    dir('task1/terraform') {
-                        sh 'terraform init'
-                        sh 'terraform apply -auto-approve -var="ssh_public_key=$(cat ${SSH_KEY_PATH}.pub)"'
-                        script {
-                            env.EC2_PUBLIC_IP = sh(script: 'terraform output instance_public_ip', returnStdout: true).trim()
-                        }
-                    }
-                }
+                deployInfrastructure()
             }
         }
 
         stage('Ensure EC2 SSH-ready') {
             steps {
-                withCredentials([sshUserPrivateKey(credentialsId: 'sec_com_ass_key_pair', keyFileVariable: 'SSH_KEY_PATH')]) {
-                    script {
-                        for (int i = 0; i < 30; i++) {
-                            def retVal = sh(script: "ssh -i ${SSH_DIR}/id_rsa.pem -o StrictHostKeyChecking=no -o ConnectionAttempts=1 ubuntu@${env.EC2_PUBLIC_IP} 'echo SSH_READY'", returnStatus: true)
-                            if (retVal == 0) {
-                                break
-                            }
-                            sleep(time: 10, unit: 'SECONDS')
-                        }
-                    }
-                }
+                waitForSshReady()
             }
         }
 
         stage('Setup Jenkins User on Target Host') {
             steps {
-                script {
-                    withCredentials([sshUserPrivateKey(credentialsId: 'sec_com_ass_key_pair', keyFileVariable: 'SSH_KEY_PATH')]) {
-                        // Check if the jenkins user exists on the target machine
-                        def userExists = sh(script: "ssh -o StrictHostKeyChecking=no -i $SSH_DIR/id_rsa.pem ubuntu@${env.EC2_PUBLIC_IP} 'getent passwd jenkins'", returnStatus: true)
-                        
-                        // If the user doesn't exist, we create it
-                        if (userExists != 0) {
-                            sh """
-                                # Creating the jenkins user
-                                ssh -o StrictHostKeyChecking=no -i $SSH_DIR/id_rsa.pem ubuntu@${env.EC2_PUBLIC_IP} "sudo useradd jenkins"
-                                
-                                # Granting the jenkins user sudo privileges
-                                ssh -o StrictHostKeyChecking=no -i $SSH_DIR/id_rsa.pem ubuntu@${env.EC2_PUBLIC_IP} "echo 'jenkins ALL=(ALL) NOPASSWD:ALL' | sudo tee -a /etc/sudoers"
-                                
-                                # Setting up the SSH directory
-                                ssh -o StrictHostKeyChecking=no -i $SSH_DIR/id_rsa.pem ubuntu@${env.EC2_PUBLIC_IP} "sudo mkdir -p /home/jenkins/.ssh && sudo chown jenkins:jenkins /home/jenkins/.ssh && sudo chmod 700 /home/jenkins/.ssh"
-                                
-                                # Copying the SSH public key using the ubuntu user and then adjusting ownership and permissions
-                                scp -o StrictHostKeyChecking=no -i $SSH_DIR/id_rsa.pem $SSH_DIR/id_rsa.pub ubuntu@${env.EC2_PUBLIC_IP}:/home/ubuntu/id_rsa.pub
-                                ssh -o StrictHostKeyChecking=no -i $SSH_DIR/id_rsa.pem ubuntu@${env.EC2_PUBLIC_IP} "sudo mv /home/ubuntu/id_rsa.pub /home/jenkins/.ssh/ && sudo chown jenkins:jenkins /home/jenkins/.ssh/id_rsa.pub && sudo chmod 600 /home/jenkins/.ssh/id_rsa.pub"
-                            """
-                        }
-                    }
-                }
+                setupJenkinsUser()
             }
         }
 
         stage('Ansible Configures MicroK8s on EC2') {
             steps {
-                script {
-                    withCredentials([sshUserPrivateKey(credentialsId: 'sec_com_ass_key_pair', keyFileVariable: 'SSH_KEY_PATH')]) {
-                        dir('task1/microk8s') {
-                            sh 'mkdir -p $SSH_DIR'
-                            sh "cp ${SSH_KEY_PATH} $SSH_DIR/id_rsa.pem"
-                            sh "chmod 600 $SSH_DIR/id_rsa.pem"
-                        
-                            writeFile file: 'ansible-ssh.cfg', text: """
-                                Host *
-                                    StrictHostKeyChecking no
-                                    IdentityFile ${SSH_DIR}/id_rsa.pem
-                                    UserKnownHostsFile /dev/null
-                            """
-                        
-                            def exists = fileExists('ansible.yml')
-                            if (!exists) {
-                                error "ansible.yml is missing in the task1/microk8s directory!"
-                            }
-                            
-                            retry(3) {
-                                sh "ANSIBLE_SSH_ARGS='-F ansible-ssh.cfg' ansible-playbook -i ${env.EC2_PUBLIC_IP}, -u ubuntu ansible.yml"
-                            }
-                        }
-                    }
-                }
+                setupMicroK8s()
             }
         }
 
         stage('Helm SonarQube on MicroK8s Deployment') {
             steps {
-                withCredentials([sshUserPrivateKey(credentialsId: 'sec_com_ass_key_pair', keyFileVariable: 'SSH_KEY_PATH')]) {
-                    dir('task1/sonar/sonarqube') {
-                        script {
-                            sh """
-                                scp -o StrictHostKeyChecking=no -i "${SSH_DIR}/id_rsa.pem" -r sonarqube ubuntu@${env.EC2_PUBLIC_IP}:/tmp
-                                ssh -o StrictHostKeyChecking=no -i "${SSH_DIR}/id_rsa.pem" ubuntu@${env.EC2_PUBLIC_IP} 'sudo microk8s helm install sonar /tmp/sonarqube && sudo microk8s helm ls'
-                            """
-                        }
-                    }
-                }
+                deploySonarQube()
             }
         }
     }
 
     post {
         always {
-            echo "Pipeline completed."
             deleteDir()
         }
         success {
@@ -148,6 +66,71 @@ pipeline {
         }
         failure {
             echo "Deployment failed! Please check the logs for more information."
+        }
+    }
+}
+
+def deployInfrastructure() {
+    withCredentials([
+        [$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'AWS_Access', accessKeyVariable: 'AWS_ACCESS_KEY_ID', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'],
+        sshUserPrivateKey(credentialsId: 'sec_com_ass_key_pair', keyFileVariable: 'SSH_KEY_PATH')
+    ]) {
+        dir('task1/terraform') {
+            sh 'terraform init'
+            sh "terraform apply -auto-approve -var=\"ssh_public_key=\$(cat ${SSH_KEY_PATH}.pub)\""
+            env.EC2_PUBLIC_IP = sh(script: 'terraform output instance_public_ip', returnStdout: true).trim()
+        }
+    }
+}
+
+def waitForSshReady() {
+    withCredentials([sshUserPrivateKey(credentialsId: 'sec_com_ass_key_pair', keyFileVariable: 'SSH_KEY_PATH')]) {
+        script {
+            def maxAttempts = 30
+            def attempts = 0
+            while (attempts < maxAttempts) {
+                def retVal = sh(script: "ssh -i ${SSH_DIR}/id_rsa.pem -o StrictHostKeyChecking=no -o ConnectionAttempts=1 ubuntu@${env.EC2_PUBLIC_IP} 'echo SSH_READY'", returnStatus: true)
+                if (retVal == 0) {
+                    break
+                }
+                sleep(time: 10, unit: 'SECONDS')
+                attempts++
+            }
+            if (attempts == maxAttempts) {
+                error("Failed to establish SSH connection after 30 attempts.")
+            }
+        }
+    }
+}
+
+def setupJenkinsUser() {
+    withCredentials([sshUserPrivateKey(credentialsId: 'sec_com_ass_key_pair', keyFileVariable: 'SSH_KEY_PATH')]) {
+        sh """
+            ssh -o StrictHostKeyChecking=no -i $SSH_DIR/id_rsa.pem ubuntu@${env.EC2_PUBLIC_IP} "sudo useradd -m jenkins || echo 'Jenkins user already exists'"
+            ssh -o StrictHostKeyChecking=no -i $SSH_DIR/id_rsa.pem ubuntu@${env.EC2_PUBLIC_IP} "sudo mkdir -p /home/jenkins/.ssh && echo \$(cat ${SSH_KEY_PATH}.pub) | sudo tee /home/jenkins/.ssh/authorized_keys > /dev/null"
+        """
+    }
+}
+
+def setupMicroK8s() {
+    withCredentials([sshUserPrivateKey(credentialsId: 'sec_com_ass_key_pair', keyFileVariable: 'SSH_KEY_PATH')]) {
+        dir('task1/microk8s') {
+            sh """
+                scp -o StrictHostKeyChecking=no -i $SSH_DIR/id_rsa.pem ansible.yml jenkins@${env.EC2_PUBLIC_IP}:/tmp
+                ssh -o StrictHostKeyChecking=no -i $SSH_DIR/id_rsa.pem jenkins@${env.EC2_PUBLIC_IP} "ansible-playbook /tmp/ansible.yml"
+            """
+        }
+    }
+}
+
+def deploySonarQube() {
+    withCredentials([sshUserPrivateKey(credentialsId: 'sec_com_ass_key_pair', keyFileVariable: 'SSH_KEY_PATH')]) {
+        dir('task1/sonar') {
+            sh """
+                ssh -o StrictHostKeyChecking=no -i $SSH_DIR/id_rsa.pem jenkins@${env.EC2_PUBLIC_IP} "microk8s helm3 repo add sonarqube https://charts.helm.sh/stable"
+                ssh -o StrictHostKeyChecking=no -i $SSH_DIR/id_rsa.pem jenkins@${env.EC2_PUBLIC_IP} "microk8s helm3 repo update"
+                ssh -o StrictHostKeyChecking=no -i $SSH_DIR/id_rsa.pem jenkins@${env.EC2_PUBLIC_IP} "microk8s helm3 install sonar sonarqube/sonarqube -f values.yaml"
+            """
         }
     }
 }
